#!/bin/bash

DEBUG=$SMUG_DEBUG
LINUX_OSRELEASE_PRETTY_NAME=

debug_latest_cmd() {
  FNNAME=$1
  RETURN=$2
  
  if [[ "$DEBUG" == true ]]; then
    echo ">>> ${FNNAME} exit with $RETURN"
  fi
}

debug_print() {
  if [[ "$DEBUG" == true ]]; then
    echo $@
  fi
}

debug_print_func_exec() {
  debug_print ">>> $1 executed"
}

detect_os() {
  debug_print "OSTYPE=$OSTYPE"
  
  case "$OSTYPE" in
    "linux-gnu")
      echo "0"
      ;;
    *)
      echo "-1"
  esac
  
  debug_print_func_exec ${FUNCNAME[0]}
}

detect_linux_distro() {
  source /etc/os-release
  
  debug_print $(cat /etc/os-release)
  debug_print "PRETTY_NAME=\"$PRETTY_NAME\""
  
  case "$PRETTY_NAME" in
    "Amazon Linux AMI 2018.03")
      LINUX_OSRELEASE_PRETTY_NAME=$PRETTY_NAME
      
      debug_print "LINUX_OSRELEASE_PRETTY_NAME=$LINUX_OSRELEASE_PRETTY_NAME"
      ;;
    *)
      echo "-1"
  esac
  
  debug_print_func_exec ${FUNCNAME[0]}
}

yum_update() {
  sudo yum -y update
  
  debug_print_func_exec ${FUNCNAME[0]}
}

setup_php73() {
  OSRELEASE_PRETTY_NAME="$1"
  debug_print "!!!!!!!$OSRELEASE_PRETTY_NAME"
  
  case "$OSRELEASE_PRETTY_NAME" in
    "Amazon Linux AMI 2018.03")
      sudo yum install -y \
        php73 \
        php73-bcmath \
        php73-devel \
        php73-mysql \
        php73-mysqlnd \
        php73-pdo \
        php73-mbstring \
        php73-gd \
        php73-xml \
        php73-xmlrpc \
        php73-mcrypt \
        php73-process \
        php73-json \
        php73-embedded \
        mod_php73 \
        php-pear
      ;;
    *)
      exit -1
  esac
  
  debug_print_func_exec ${FUNCNAME[0]}
}

remove_php_already_installed() {
  sudo yum remove -y httpd* php* mod_php*
  
  debug_print_func_exec ${FUNCNAME[0]}
}

detect_os
detect_linux_distro
yum_update
remove_php_already_installed
setup_php73 "$LINUX_OSRELEASE_PRETTY_NAME"

export SMUG_DEBUG=false